import type { Metadata } from "next";
import { Inter, Bodoni_Moda } from "next/font/google";
import "./globals.css";
import MenuButton from "@/components/menu/MenuButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body  className={`${inter.className} text-white relative min-h-screen bg-slate-800 text-black`}>
        {children}
      <MenuButton/>
        </body>
    </html>
  );
}
